
// ANIMAIS
[
  { "_id": "animal01", "nome": "Focinho", "idade": 3, "tipo": "Cachorro", "raça": "Vira-lata", "peso": 15.2, "dono": "dono01" },
  { "_id": "animal02", "nome": "Fênix", "idade": 2, "tipo": "Gato", "raça": "Siamês", "peso": 4.1, "dono": "dono02" },
  { "_id": "animal03", "nome": "Pé de Pano", "idade": 5, "tipo": "Cachorro", "raça": "Golden Retriever", "peso": 28.5, "dono": "dono03" },
  { "_id": "animal04", "nome": "Banzé", "idade": 1, "tipo": "Cachorro", "raça": "Poodle", "peso": 5.7, "dono": "dono04" },
  { "_id": "animal05", "nome": "Pompom", "idade": 4, "tipo": "Coelho", "raça": "Holandês Anão", "peso": 1.8, "dono": "dono05" },
  { "_id": "animal06", "nome": "Sombra", "idade": 7, "tipo": "Gato", "raça": "Persa", "peso": 5.0, "dono": "dono06" },
  { "_id": "animal07", "nome": "Faísca", "idade": 2, "tipo": "Cachorro", "raça": "Labrador", "peso": 25.0, "dono": "dono07" },
  { "_id": "animal08", "nome": "Mimosa", "idade": 6, "tipo": "Gato", "raça": "Vira-lata", "peso": 3.5, "dono": "dono08" },
  { "_id": "animal09", "nome": "Trovão", "idade": 3, "tipo": "Cachorro", "raça": "Pastor Alemão", "peso": 32.1, "dono": "dono09" },
  { "_id": "animal10", "nome": "Whisky", "idade": 1, "tipo": "Cachorro", "raça": "Shih Tzu", "peso": 6.3, "dono": "dono10" },
  { "_id": "animal11", "nome": "Gato Félix", "idade": 4, "tipo": "Gato", "raça": "Angorá", "peso": 4.7, "dono": "dono11" },
  { "_id": "animal12", "nome": "Max", "idade": 5, "tipo": "Cachorro", "raça": "Husky Siberiano", "peso": 22.8, "dono": "dono12" },
  { "_id": "animal13", "nome": "Lady", "idade": 2, "tipo": "Gato", "raça": "Maine Coon", "peso": 6.5, "dono": "dono13" },
  { "_id": "animal14", "nome": "Bingo", "idade": 3, "tipo": "Cachorro", "raça": "Beagle", "peso": 11.4, "dono": "dono14" },
  { "_id": "animal15", "nome": "Snowball", "idade": 1, "tipo": "Coelho", "raça": "Mini Rex", "peso": 2.1, "dono": "dono15" },
  { "_id": "animal16", "nome": "Bolt", "idade": 4, "tipo": "Cachorro", "raça": "Pastor Alemão", "peso": 31.0, "dono": "dono16" },
  { "_id": "animal17", "nome": "Miau", "idade": 6, "tipo": "Gato", "raça": "Vira-lata", "peso": 3.9, "dono": "dono17" },
  { "_id": "animal18", "nome": "Pipoca", "idade": 2, "tipo": "Cachorro", "raça": "Yorkshire Terrier", "peso": 3.4, "dono": "dono18" },
  { "_id": "animal19", "nome": "Zeus", "idade": 7, "tipo": "Gato", "raça": "Persa", "peso": 5.2, "dono": "dono19" },
  { "_id": "animal20", "nome": "Apolo", "idade": 1, "tipo": "Cachorro", "raça": "Dachshund", "peso": 7.8, "dono": "dono20" },
  { "_id": "animal21", "nome": "Cacau", "idade": 3, "tipo": "Cachorro", "raça": "Bulldog Francês", "peso": 10.5, "dono": "dono21" },
  { "_id": "animal22", "nome": "Duque", "idade": 5, "tipo": "Gato", "raça": "Siamês", "peso": 4.5, "dono": "dono22" },
  { "_id": "animal23", "nome": "Kiwi", "idade": 2, "tipo": "Pássaro", "raça": "Calopsita", "peso": 0.1, "dono": "dono23" },
  { "_id": "animal24", "nome": "Bolinha", "idade": 4, "tipo": "Cachorro", "raça": "Lulu da Pomerânia", "peso": 3.1, "dono": "dono24" },
  { "_id": "animal25", "nome": "Amora", "idade": 1, "tipo": "Gato", "raça": "Vira-lata", "peso": 2.9, "dono": "dono25" },
  { "_id": "animal26", "nome": "Sansão", "idade": 6, "tipo": "Cachorro", "raça": "São Bernardo", "peso": 75.0, "dono": "dono26" },
  { "_id": "animal27", "nome": "Estrela", "idade": 3, "tipo": "Gato", "raça": "Siberiano", "peso": 5.8, "dono": "dono27" },
  { "_id": "animal28", "nome": "Leão", "idade": 5, "tipo": "Cachorro", "raça": "Rottweiler", "peso": 45.3, "dono": "dono28" },
  { "_id": "animal29", "nome": "Princesa", "idade": 2, "tipo": "Gato", "raça": "Persa", "peso": 4.0, "dono": "dono29" },
  { "_id": "animal30", "nome": "Rex", "idade": 4, "tipo": "Cachorro", "raça": "Boxer", "peso": 29.6, "dono": "dono30" },
  { "_id": "animal31", "nome": "Milo", "idade": 1, "tipo": "Cachorro", "raça": "Border Collie", "peso": 18.0, "dono": "dono31" },
  { "_id": "animal32", "nome": "Pudim", "idade": 2, "tipo": "Gato", "raça": "Shorthair Americano", "peso": 3.7, "dono": "dono32" },
  { "_id": "animal33", "nome": "Thor", "idade": 3, "tipo": "Cachorro", "raça": "Golden Retriever", "peso": 27.5, "dono": "dono33" },
  { "_id": "animal34", "nome": "Cleo", "idade": 4, "tipo": "Gato", "raça": "Bengala", "peso": 4.8, "dono": "dono34" },
  { "_id": "animal35", "nome": "Cookie", "idade": 1, "tipo": "Cachorro", "raça": "Cocker Spaniel", "peso": 12.3, "dono": "dono35" },
  { "_id": "animal36", "nome": "Tigre", "idade": 5, "tipo": "Gato", "raça": "Vira-lata", "peso": 5.1, "dono": "dono36" },
  { "_id": "animal37", "nome": "Bruce", "idade": 2, "tipo": "Cachorro", "raça": "Pit Bull", "peso": 26.8, "dono": "dono37" },
  { "_id": "animal38", "nome": "Pequeno", "idade": 3, "tipo": "Hamster", "raça": "Sírio", "peso": 0.2, "dono": "dono38" },
  { "_id": "animal39", "nome": "Loki", "idade": 4, "tipo": "Cachorro", "raça": "Buldogue Inglês", "peso": 23.5, "dono": "dono39" },
  { "_id": "animal40", "nome": "Sol", "idade": 1, "tipo": "Gato", "raça": "Ragdoll", "peso": 5.5, "dono": "dono40" },
  { "_id": "animal41", "nome": "Pandora", "idade": 6, "tipo": "Cachorro", "raça": "Akita", "peso": 35.0, "dono": "dono41" },
  { "_id": "animal42", "nome": "Lua", "idade": 3, "tipo": "Gato", "raça": "Shorthair Inglês", "peso": 4.3, "dono": "dono42" },
  { "_id": "animal43", "nome": "Tobi", "idade": 2, "tipo": "Cachorro", "raça": "Chihuahua", "peso": 2.1, "dono": "dono43" },
  { "_id": "animal44", "nome": "Jade", "idade": 5, "tipo": "Gato", "raça": "Vira-lata", "peso": 3.8, "dono": "dono44" },
  { "_id": "animal45", "nome": "Flash", "idade": 1, "tipo": "Cachorro", "raça": "Whippet", "peso": 10.1, "dono": "dono45" },
  { "_id": "animal46", "nome": "Odin", "idade": 4, "tipo": "Cachorro", "raça": "Doberman", "peso": 38.0, "dono": "dono46" },
  { "_id": "animal47", "nome": "Smudge", "idade": 2, "tipo": "Gato", "raça": "Sphynx", "peso": 3.6, "dono": "dono47" },
  { "_id": "animal48", "nome": "Kiko", "idade": 3, "tipo": "Cachorro", "raça": "Pug", "peso": 8.5, "dono": "dono48" },
  { "_id": "animal49", "nome": "Whisper", "idade": 1, "tipo": "Cachorro", "raça": "Galgo Afegão", "peso": 20.0, "dono": "dono49" },
  { "_id": "animal50", "nome": "Nala", "idade": 2, "tipo": "Gato", "raça": "Vira-lata", "peso": 3.2, "dono": "dono50" }
]
  
  db.animal.insertMany([
  { "nome": "Jubileu", "idade": 5, "tipo": "Cachorro", "raça": "Golden Retriever", "peso": 32.5 },
  { "nome": "Amora", "idade": 2, "tipo": "Gato", "raça": "Siamês", "peso": 4.1 },
  { "nome": "Bartholomeu", "idade": 10, "tipo": "Cachorro", "raça": "Bulldog", "peso": 25.0 },
  { "nome": "Pérola", "idade": 1, "tipo": "Gato", "raça": "Persa", "peso": 3.5 },
  { "nome": "Thor", "idade": 8, "tipo": "Cachorro", "raça": "Pastor Alemão", "peso": 40.2 },
  { "nome": "Fofura", "idade": 3, "tipo": "Gato", "raça": "Maine Coon", "peso": 6.8 },
  { "nome": "Amora", "idade": 6, "tipo": "Cachorro", "raça": "Labrador", "peso": 28.9 },
  { "nome": "Simba", "idade": 4, "tipo": "Gato", "raça": "Angorá", "peso": 4.5 },
  { "nome": "Lucky", "idade": 7, "tipo": "Cachorro", "raça": "Beagle", "peso": 15.3 },
  { "nome": "Lola", "idade": 2, "tipo": "Gato", "raça": "Ragdoll", "peso": 5.9 },
  { "nome": "Maximus", "idade": 1, "tipo": "Cachorro", "raça": "Poodle", "peso": 5.1 },
  { "nome": "Princesa", "idade": 5, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.8 },
  { "nome": "Buddy", "idade": 9, "tipo": "Cachorro", "raça": "Boxer", "peso": 30.7 },
  { "nome": "Kiwi", "idade": 3, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.0 },
  { "nome": "Zeca", "idade": 11, "tipo": "Cachorro", "raça": "Dachshund", "peso": 9.5 },
  { "nome": "Chico", "idade": 6, "tipo": "Gato", "raça": "Bengal", "peso": 5.2 },
  { "nome": "Meg", "idade": 4, "tipo": "Cachorro", "raça": "Chihuahua", "peso": 2.1 },
  { "nome": "Estrela", "idade": 8, "tipo": "Gato", "raça": "Himalaio", "peso": 4.9 },
  { "nome": "Bethoven", "idade": 7, "tipo": "Cachorro", "raça": "São Bernardo", "peso": 75.0 },
  { "nome": "Luna", "idade": 1, "tipo": "Gato", "raça": "Britânico de Pelo Curto", "peso": 4.3 },
  { "nome": "Duda", "idade": 3, "tipo": "Cachorro", "raça": "Shih Tzu", "peso": 6.5 },
  { "nome": "Mimi", "idade": 10, "tipo": "Gato", "raça": "Exótico", "peso": 3.9 },
  { "nome": "Bob", "idade": 5, "tipo": "Cachorro", "raça": "Rottweiler", "peso": 55.4 },
  { "nome": "Sasha", "idade": 2, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.7 },
  { "nome": "Jake", "idade": 6, "tipo": "Cachorro", "raça": "Husky Siberiano", "peso": 24.8 },
  { "nome": "Oliver", "idade": 4, "tipo": "Gato", "raça": "Sphynx", "peso": 4.6 },
  { "nome": "Fred", "idade": 8, "tipo": "Cachorro", "raça": "Border Collie", "peso": 20.1 },
  { "nome": "Kiko", "idade": 3, "tipo": "Gato", "raça": "Azul Russo", "peso": 4.2 },
  { "nome": "Mel", "idade": 1, "tipo": "Cachorro", "raça": "Maltês", "peso": 3.8 },
  { "nome": "Gigi", "idade": 5, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.6 },
  { "nome": "Tobias", "idade": 9, "tipo": "Cachorro", "raça": "Doberman", "peso": 42.0 },
  { "nome": "Nina", "idade": 2, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.5 },
  { "nome": "Bidu", "idade": 7, "tipo": "Cachorro", "raça": "Vira-lata", "peso": 18.0 },
  { "nome": "Bilu", "idade": 4, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.1 },
  { "nome": "Scooby", "idade": 6, "tipo": "Cachorro", "raça": "Dogue Alemão", "peso": 60.5 },
  { "nome": "Zoe", "idade": 1, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.9 },
  { "nome": "Mickey", "idade": 10, "tipo": "Cachorro", "raça": "Pinscher", "peso": 4.0 },
  { "nome": "Nino", "idade": 3, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.4 },
  { "nome": "Apollo", "idade": 2, "tipo": "Cachorro", "raça": "Cocker Spaniel", "peso": 10.5 },
  { "nome": "Tico", "idade": 5, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.2 },
  { "nome": "Jack", "idade": 4, "tipo": "Cachorro", "raça": "Basset Hound", "peso": 18.8 },
  { "nome": "Kira", "idade": 6, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.7 },
  { "nome": "Zeus", "idade": 8, "tipo": "Cachorro", "raça": "Pit Bull", "peso": 27.3 },
  { "nome": "Chloé", "idade": 1, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.1 },
  { "nome": "Duque", "idade": 3, "tipo": "Cachorro", "raça": "Bernese", "peso": 45.9 },
  { "nome": "Pandora", "idade": 7, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.0 },
  { "nome": "Hulk", "idade": 5, "tipo": "Cachorro", "raça": "Bull Terrier", "peso": 23.5 },
  { "nome": "Romeu", "idade": 2, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.6 },
  { "nome": "Dino", "idade": 9, "tipo": "Cachorro", "raça": "Chow Chow", "peso": 26.7 },
  { "nome": "Penélope", "idade": 4, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.3 },
  { "nome": "Bart", "idade": 6, "tipo": "Cachorro", "raça": "Pug", "peso": 8.0 },
  { "nome": "Leona", "idade": 3, "tipo": "Gato", "raça": "Sem raça definida", "peso": 5.0 },
  { "nome": "Otto", "idade": 1, "tipo": "Cachorro", "raça": "Pastor de Shetland", "peso": 8.5 },
  { "nome": "Pipoca", "idade": 5, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.4 },
  { "nome": "Ringo", "idade": 10, "tipo": "Cachorro", "raça": "Shar Pei", "peso": 20.4 },
  { "nome": "Íris", "idade": 2, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.5 },
  { "nome": "Kobe", "idade": 7, "tipo": "Cachorro", "raça": "Akita", "peso": 35.1 },
  { "nome": "Tigre", "idade": 4, "tipo": "Gato", "raça": "Sem raça definida", "peso": 5.1 },
  { "nome": "Nala", "idade": 3, "tipo": "Cachorro", "raça": "Siberiano", "peso": 22.0 },
  { "nome": "Flor", "idade": 6, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.7 },
  { "nome": "Apolo", "idade": 5, "tipo": "Cachorro", "raça": "Galgo Afegão", "peso": 28.0 },
  { "nome": "Whisky", "idade": 2, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.0 },
  { "nome": "Spike", "idade": 11, "tipo": "Cachorro", "raça": "Vira-lata", "peso": 20.0 },
  { "nome": "Biscoito", "idade": 1, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.8 },
  { "nome": "Gohan", "idade": 4, "tipo": "Cachorro", "raça": "Golden Retriever", "peso": 31.0 },
  { "nome": "Cleo", "idade": 3, "tipo": "Gato", "raça": "Siamês", "peso": 4.5 },
  { "nome": "Gus", "idade": 7, "tipo": "Cachorro", "raça": "Labrador", "peso": 29.5 },
  { "nome": "Milo", "idade": 5, "tipo": "Gato", "raça": "Persa", "peso": 3.7 },
  { "nome": "Hades", "idade": 9, "tipo": "Cachorro", "raça": "Pastor Alemão", "peso": 41.0 },
  { "nome": "Eva", "idade": 2, "tipo": "Gato", "raça": "Maine Coon", "peso": 7.0 },
  { "nome": "Pongo", "idade": 6, "tipo": "Cachorro", "raça": "Dálmata", "peso": 25.5 },
  { "nome": "Kika", "idade": 4, "tipo": "Gato", "raça": "Angorá", "peso": 4.2 },
  { "nome": "Luke", "idade": 1, "tipo": "Cachorro", "raça": "Pug", "peso": 7.5 },
  { "nome": "Maya", "idade": 8, "tipo": "Gato", "raça": "Ragdoll", "peso": 6.1 },
  { "nome": "Lupi", "idade": 3, "tipo": "Cachorro", "raça": "Poodle", "peso": 6.0 },
  { "nome": "Tita", "idade": 6, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.9 },
  { "nome": "Rocky", "idade": 5, "tipo": "Cachorro", "raça": "Boxer", "peso": 31.5 },
  { "nome": "Félix", "idade": 2, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.1 },
  { "nome": "Kadu", "idade": 10, "tipo": "Cachorro", "raça": "Dachshund", "peso": 9.8 },
  { "nome": "Chica", "idade": 4, "tipo": "Gato", "raça": "Bengal", "peso": 5.4 },
  { "nome": "Zeus", "idade": 2, "tipo": "Cachorro", "raça": "São Bernardo", "peso": 78.0 },
  { "nome": "Nina", "idade": 1, "tipo": "Gato", "raça": "Britânico de Pelo Curto", "peso": 4.5 },
  { "nome": "Flash", "idade": 4, "tipo": "Cachorro", "raça": "Chihuahua", "peso": 2.2 },
  { "nome": "Chami", "idade": 9, "tipo": "Gato", "raça": "Himalaio", "peso": 5.0 },
  { "nome": "Loki", "idade": 6, "tipo": "Cachorro", "raça": "Rottweiler", "peso": 56.1 },
  { "nome": "Amélie", "idade": 3, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.8 },
  { "nome": "Buddy", "idade": 8, "tipo": "Cachorro", "raça": "Husky Siberiano", "peso": 25.0 },
  { "nome": "Bartolomeu", "idade": 5, "tipo": "Gato", "raça": "Sphynx", "peso": 4.8 },
  { "nome": "Fred", "idade": 7, "tipo": "Cachorro", "raça": "Border Collie", "peso": 20.5 },
  { "nome": "Chico", "idade": 4, "tipo": "Gato", "raça": "Azul Russo", "peso": 4.3 },
  { "nome": "Mel", "idade": 2, "tipo": "Cachorro", "raça": "Maltês", "peso": 4.0 },
  { "nome": "Gigi", "idade": 6, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.7 },
  { "nome": "Tobias", "idade": 10, "tipo": "Cachorro", "raça": "Doberman", "peso": 43.0 },
  { "nome": "Nina", "idade": 3, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.6 },
  { "nome": "Bidu", "idade": 8, "tipo": "Cachorro", "raça": "Vira-lata", "peso": 19.5 },
  { "nome": "Bilu", "idade": 5, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.2 },
  { "nome": "Scooby", "idade": 7, "tipo": "Cachorro", "raça": "Dogue Alemão", "peso": 62.0 },
  { "nome": "Zoe", "idade": 2, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.0 },
  { "nome": "Mickey", "idade": 11, "tipo": "Cachorro", "raça": "Pinscher", "peso": 4.1 },
  { "nome": "Nino", "idade": 4, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.5 },
  { "nome": "Apollo", "idade": 3, "tipo": "Cachorro", "raça": "Cocker Spaniel", "peso": 11.0 },
  { "nome": "Tico", "idade": 6, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.3 },
  { "nome": "Jack", "idade": 5, "tipo": "Cachorro", "raça": "Basset Hound", "peso": 19.0 },
  { "nome": "Kira", "idade": 7, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.8 },
  { "nome": "Zeus", "idade": 9, "tipo": "Cachorro", "raça": "Pit Bull", "peso": 28.0 },
  { "nome": "Chloé", "idade": 2, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.2 },
  { "nome": "Duque", "idade": 4, "tipo": "Cachorro", "raça": "Bernese", "peso": 46.5 },
  { "nome": "Pandora", "idade": 8, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.1 },
  { "nome": "Hulk", "idade": 6, "tipo": "Cachorro", "raça": "Bull Terrier", "peso": 24.0 },
  { "nome": "Romeu", "idade": 3, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.7 },
  { "nome": "Dino", "idade": 10, "tipo": "Cachorro", "raça": "Chow Chow", "peso": 27.0 },
  { "nome": "Penélope", "idade": 5, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.4 },
  { "nome": "Bart", "idade": 7, "tipo": "Cachorro", "raça": "Pug", "peso": 8.1 },
  { "nome": "Leona", "idade": 4, "tipo": "Gato", "raça": "Sem raça definida", "peso": 5.1 },
  { "nome": "Otto", "idade": 2, "tipo": "Cachorro", "raça": "Pastor de Shetland", "peso": 8.6 },
  { "nome": "Pipoca", "idade": 6, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.5 },
  { "nome": "Ringo", "idade": 11, "tipo": "Cachorro", "raça": "Shar Pei", "peso": 20.6 },
  { "nome": "Íris", "idade": 3, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.6 },
  { "nome": "Kobe", "idade": 8, "tipo": "Cachorro", "raça": "Akita", "peso": 35.5 },
  { "nome": "Tigre", "idade": 5, "tipo": "Gato", "raça": "Sem raça definida", "peso": 5.2 },
  { "nome": "Nala", "idade": 4, "tipo": "Cachorro", "raça": "Siberiano", "peso": 22.5 },
  { "nome": "Flor", "idade": 7, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.8 },
  { "nome": "Apolo", "idade": 6, "tipo": "Cachorro", "raça": "Galgo Afegão", "peso": 28.5 },
  { "nome": "Whisky", "idade": 3, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.1 },
  { "nome": "Spike", "idade": 12, "tipo": "Cachorro", "raça": "Vira-lata", "peso": 21.0 },
  { "nome": "Biscoito", "idade": 2, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.9 },
  { "nome": "Gohan", "idade": 5, "tipo": "Cachorro", "raça": "Golden Retriever", "peso": 32.0 },
  { "nome": "Cleo", "idade": 4, "tipo": "Gato", "raça": "Siamês", "peso": 4.6 },
  { "nome": "Gus", "idade": 8, "tipo": "Cachorro", "raça": "Labrador", "peso": 30.0 },
  { "nome": "Milo", "idade": 6, "tipo": "Gato", "raça": "Persa", "peso": 3.8 },
  { "nome": "Hades", "idade": 10, "tipo": "Cachorro", "raça": "Pastor Alemão", "peso": 42.0 },
  { "nome": "Eva", "idade": 3, "tipo": "Gato", "raça": "Maine Coon", "peso": 7.2 },
  { "nome": "Pongo", "idade": 7, "tipo": "Cachorro", "raça": "Dálmata", "peso": 26.0 },
  { "nome": "Kika", "idade": 5, "tipo": "Gato", "raça": "Angorá", "peso": 4.3 },
  { "nome": "Luke", "idade": 2, "tipo": "Cachorro", "raça": "Pug", "peso": 7.6 },
  { "nome": "Maya", "idade": 9, "tipo": "Gato", "raça": "Ragdoll", "peso": 6.2 },
  { "nome": "Lupi", "idade": 4, "tipo": "Cachorro", "raça": "Poodle", "peso": 6.1 },
  { "nome": "Tita", "idade": 7, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.0 },
  { "nome": "Rocky", "idade": 6, "tipo": "Cachorro", "raça": "Boxer", "peso": 32.0 },
  { "nome": "Félix", "idade": 3, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.2 },
  { "nome": "Kadu", "idade": 11, "tipo": "Cachorro", "raça": "Dachshund", "peso": 10.0 },
  { "nome": "Chica", "idade": 5, "tipo": "Gato", "raça": "Bengal", "peso": 5.5 },
  { "nome": "Zeus", "idade": 3, "tipo": "Cachorro", "raça": "São Bernardo", "peso": 80.0 },
  { "nome": "Nina", "idade": 2, "tipo": "Gato", "raça": "Britânico de Pelo Curto", "peso": 4.6 },
  { "nome": "Flash", "idade": 5, "tipo": "Cachorro", "raça": "Chihuahua", "peso": 2.3 },
  { "nome": "Chami", "idade": 10, "tipo": "Gato", "raça": "Himalaio", "peso": 5.1 },
  { "nome": "Loki", "idade": 7, "tipo": "Cachorro", "raça": "Rottweiler", "peso": 57.0 },
  { "nome": "Amélie", "idade": 4, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.9 },
  { "nome": "Buddy", "idade": 9, "tipo": "Cachorro", "raça": "Husky Siberiano", "peso": 25.5 },
  { "nome": "Bartolomeu", "idade": 6, "tipo": "Gato", "raça": "Sphynx", "peso": 4.9 },
  { "nome": "Simba", "idade": 5, "tipo": "Cachorro", "raça": "Labrador", "peso": 30.5 },
  { "nome": "Odin", "idade": 2, "tipo": "Gato", "raça": "Siamês", "peso": 4.3 },
  { "nome": "Fido", "idade": 8, "tipo": "Cachorro", "raça": "Bulldog", "peso": 26.0 },
  { "nome": "Jade", "idade": 3, "tipo": "Gato", "raça": "Persa", "peso": 3.6 },
  { "nome": "Hércules", "idade": 6, "tipo": "Cachorro", "raça": "Pastor Alemão", "peso": 41.5 },
  { "nome": "Athena", "idade": 1, "tipo": "Gato", "raça": "Maine Coon", "peso": 6.9 },
  { "nome": "Bento", "idade": 4, "tipo": "Cachorro", "raça": "Labrador", "peso": 29.0 },
  { "nome": "Misty", "idade": 7, "tipo": "Gato", "raça": "Angorá", "peso": 4.6 },
  { "nome": "Toby", "idade": 9, "tipo": "Cachorro", "raça": "Beagle", "peso": 16.0 },
  { "nome": "Daisy", "idade": 4, "tipo": "Gato", "raça": "Ragdoll", "peso": 6.0 },
  { "nome": "Marley", "idade": 3, "tipo": "Cachorro", "raça": "Poodle", "peso": 5.5 },
  { "nome": "Sushi", "idade": 6, "tipo": "Gato", "raça": "Sem raça definida", "peso": 4.0 },
  { "nome": "Rocky", "idade": 1, "tipo": "Cachorro", "raça": "Boxer", "peso": 28.0 },
  { "nome": "Cleopatra", "idade": 8, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.9 },
  { "nome": "Davi", "idade": 5, "tipo": "Cachorro", "raça": "Dachshund", "peso": 9.2 },
  { "nome": "Gandalf", "idade": 2, "tipo": "Gato", "raça": "Bengal", "peso": 5.3 },
  { "nome": "Chiquinha", "idade": 7, "tipo": "Cachorro", "raça": "Chihuahua", "peso": 2.5 },
  { "nome": "Fiona", "idade": 10, "tipo": "Gato", "raça": "Himalaio", "peso": 5.2 },
  { "nome": "Brutus", "idade": 4, "tipo": "Cachorro", "raça": "São Bernardo", "peso": 77.0 },
  { "nome": "Gizmo", "idade": 3, "tipo": "Gato", "raça": "Britânico de Pelo Curto", "peso": 4.4 },
  { "nome": "Pépe", "idade": 6, "tipo": "Cachorro", "raça": "Shih Tzu", "peso": 6.8 },
  { "nome": "Bolinha", "idade": 12, "tipo": "Gato", "raça": "Exótico", "peso": 4.1 },
  { "nome": "Sansão", "idade": 7, "tipo": "Cachorro", "raça": "Rottweiler", "peso": 58.0 },
  { "nome": "Tequila", "idade": 1, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.4 },
  { "nome": "Bolt", "idade": 9, "tipo": "Cachorro", "raça": "Husky Siberiano", "peso": 26.0 },
  { "nome": "Pixel", "idade": 6, "tipo": "Gato", "raça": "Sphynx", "peso": 5.0 },
  { "nome": "Lorde", "idade": 10, "tipo": "Cachorro", "raça": "Border Collie", "peso": 21.0 },
  { "nome": "Gatinho", "idade": 5, "tipo": "Gato", "raça": "Azul Russo", "peso": 4.5 },
  { "nome": "Pitty", "idade": 3, "tipo": "Cachorro", "raça": "Maltês", "peso": 4.2 },
  { "nome": "Lilica", "idade": 7, "tipo": "Gato", "raça": "Sem raça definida", "peso": 3.8 }
])